version: '3'
services:
  yara.europe.gateway:
    build:
      context: .
      dockerfile: Dockerfile.yarn.local
    ports:
      - '5000:5000'
    volumes:
      - '.:/opt/app'
    depends_on:
      - elasticsearch
      - tankmix
      - grassn
      - yara.europe.database
    environment:
      PORT: 5000
      ELASTIC_SEARCH_URL: 'http://elasticsearch:9200'
      NODE_ENV: development
      LOCAL_SERVICES: tankmix,grassn
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.2'
    environment:
      - cluster.name=es-docker-cluster
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - http.cors.allow-origin=*
      - http.cors.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
  yara.europe.database:
    build: ./database_init_local
    ports:
      - '5565:5432'
    environment:
      POSTGRES_DB: YaraEurope
      POSTGRES_USER: yara
      POSTGRES_PASSWORD: yara123
  tankmix:
    build:
      context: .
      dockerfile: Dockerfile.yarn.local
    depends_on:
      - yara.europe.database
    ports:
      - '5001:5001'
    volumes:
      - '../yara-eu-tankmix:/opt/app'
    environment:
      PORT: '5001'
      POSTGRES_DB: YaraEurope
      POSTGRES_USER: yara
      POSTGRES_PASSWORD: yara123
      POSTGRES_PORT: '5432'
      POSTGRES_HOST: yara.europe.database
      POSTGRES_POOLSIZE: '10'
      NODE_ENV: development
      ELASTIC_SEARCH_URL: 'http://elasticsearch:9200'
  grassn:
    build:
      context: .
      dockerfile: Dockerfile.yarn.local
    depends_on:
      - yara.europe.database
    ports:
      - '5002:5002'
    volumes:
      - '../yara-eu-grassn:/opt/app'
    environment:
      PORT: '5002'
      POSTGRES_DB: YaraEurope
      POSTGRES_USER: yara
      POSTGRES_PASSWORD: yara123
      POSTGRES_PORT: '5432'
      POSTGRES_HOST: yara.europe.database
      POSTGRES_POOLSIZE: '10'
      NODE_ENV: development
      ELASTIC_SEARCH_URL: 'http://elasticsearch:9200'
